
/* 
	CONVERSÃO DE DADOS UTILIZAMOS CAST OU CONVERT

	DIFERENÇA ENTRE CAST E CONVERT => AMBAS FAZEM A MESMA COISA MAS CAST É USADO 
	NO PADRÃO SQL (LINGUAGEM) EXISTINDO EM OUTRO BANCOS DE DADOS COMO ORACLE, MYSQL.
	CONVERT ESPECÍFICO UTILIZADO NO SQL SERVER E MUITO MAIS PODEROSO NA CONVERSÃO POR SE TRATAR
	DE UM RECURSO DO PROPRIO PROGRAMA.

	UTILIZAR SEMPRE O CONVERT NO SQL SERVER

 */

 
SELECT CONVERT(VARCHAR, GETDATE(), 101)

SELECT CONVERT(VARCHAR, GETDATE(), 113)

SELECT CONVERT(VARCHAR, GETDATE(), 130)

SELECT CONVERT(decimal(10,5), 193.57)

SELECT * FROM [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  [PREÇO DE LISTA] 
FROM [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' + 'R$ ' + CONVERT(VARCHAR, [PREÇO DE LISTA]) 
FROM [TABELA DE PRODUTOS]


SELECT CONCAT('O cliente ', TC.NOME, ' faturou R$ ', 
CONVERT(VARCHAR, CONVERT(DECIMAL(15,2), SUM(INF.QUANTIDADE * INF.[PREÇO]))), ' no ano de ',   
CONVERT(VARCHAR, YEAR(NF.DATA))) AS SENTENCA FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
INNER JOIN [TABELA DE CLIENTES] TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA) = 2016
GROUP BY TC.NOME, YEAR(DATA)