
SELECT CEILING(12.333223)		/* RETORNA O MAIRO INTEIRO DO NUMERO USADO NA FUNÇÃO OU COMO PARÂMETRO */ 

SELECT FLOOR(12.333223)			/* RETORNA O MENOR INTEIRO DO NUMERO USADO NA FUNÇÃO OU COMO PARÂMETRO */ 

SELECT RAND()					/* GERA UM NUMERO ALEATORIO - RAND ([SEED]) - CASO NAO ESPECIFÍQUE IRÁ UTILIZAR UM NÚMERO ALEATÓRIO DO CPU  */ 

SELECT ROUND(12.33323323, 2)	/* ARREDONDA UM NUMERO UTILIZANDO O NUMERO DE PRECISÃO COLOCADO NA FUNÇÃO  */ 

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT [QUANTIDADE], [PREÇO], ROUND(([QUANTIDADE] * [PREÇO]),1) FROM [ITENS NOTAS FISCAIS]

SELECT YEAR(DATA), FLOOR(SUM(IMPOSTO * (QUANTIDADE * PREÇO))) 
FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA) = 2016
GROUP BY YEAR(DATA)